services:
  lotto-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lotto-bot
    restart: unless-stopped

    environment:
      - TZ=Asia/Seoul

    env_file:
      - ./.env
      - ./credentials

    volumes:
      - ./log:/app/log
