services:
  lottobot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lottobot
    restart: unless-stopped

    environment:
      - TZ=Asia/Seoul

    # Load environment variables from .env file
    env_file:
      - ${HOME}/.secrets/lottobot/.env
      - ${HOME}/.secrets/lottobot/credentials

    volumes:
      # Persistent log directory (read-write)
      - ${HOME}/docker/lottobot/logs:/app/log

    # No ports needed - cron-based application

    # Keep container running with cron daemon
    tty: true
    stdin_open: true

    # Optional: Add labels for organization
    labels:
      - "app=lottobot"
      - "type=scheduler"
      - "description=Korean Lotto 6/45 automated checker and purchaser"
