services:
  lottobot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lottobot
    restart: unless-stopped

    environment:
      - TZ=Asia/Seoul

    env_file:
      - ${HOME}/.secrets/lottobot/.env
      - ${HOME}/.secrets/lottobot/credentials

    volumes:
      - ${HOME}/docker/lottobot/logs:/app/log
